[project]
name = "stock-backtrader-web-app"
version = "0.1.0"  # 必须添加的版本号
requires-python = ">=3.8"
dependencies = [
    "streamlit>=1.32",
    "backtrader>=1.9.78",
    "akshare>=1.12",
    "pandas>=2.1",
    "matplotlib>=3.8"
]
