current_env: "dev"
logger:
  driver: loguru
  level: debug
  write_to:
    - name: console
#      args:
#         format: '"<green>{time:YYYY-MM-DD HH:mm:ss}</green> | "
#            "<level>{level: <8}</level> | "
#            "<cyan>{thread.name}</cyan> | "
#            "<cyan>{name}</cyan>:<cyan>{function}</cyan>:<cyan>{line}</cyan> | "
#            "<cyan>{function}</cyan> |"
#            "<level>{message}</level> |"
#            "<yellow>{extra}</yellow>"'
    - name: file
      args:
        path: "logs/app_{time:YYYY-MM-DD}.log"
        retention: "30 days"

