sqllog: false
initTable: false
mainConn:
  host: "127.0.0.1"
  port: 3306
  user: "root"
  password: "root"
  charset: "utf8mb4"
jobConn:
  host: "127.0.0.1"
  port: 3306
  user: "root"
  password: "root"
  database: "zvt_jobs"