jq_username: ""
jq_password: ""
http_proxy: "127.0.0.1:1087"
https_proxy: "127.0.0.1:1087"
smtp_host: "smtpdm.aliyun.com"
smtp_port: "80"
email_username: ""
email_password: ""
wechat_app_id: ""
wechat_app_secrect: ""
qiye_wechat_bot_token: ""
qmt_mini_data_path: "E:\\qmt\\userdata_mini"
qmt_account_id: ""
moonshot_api_key: ""
qwen_api_key: ""
sqllog: false
initTable: false
mainConn:
  host: "127.0.0.1"
  port: 3306
  user: "root"
  password: "root"
  charset: "utf8mb4"
jobConn:
  host: "127.0.0.1"
  port: 3306
  user: "root"
  password: "root"
  database: "zvt_jobs"