# -*- coding: utf-8 -*-
# this file is generated by gen_kdata_schema function, dont't change it
from sqlalchemy.orm import declarative_base

from core.contract.register import register_schema
from core.domain.constants import stock_db_name
from core.domain.quotes import StockKdataCommon

KdataBase = declarative_base()


class Stock1monKdata(KdataBase, StockKdataCommon):
    __tablename__ = "stock_1mon_kdata"


register_schema(
    providers=["em", "qmt", "joinquant"], db_name=stock_db_name, schema_base=KdataBase, entity_type="stock"
)


# the __all__ is generated
__all__ = ["Stock1monKdata"]
